version: '3.3'

services:
  traefik:
    image: stefanscherer/traefik-windows:v1.7.12
    volumes:
      - source: 'C:/traefik/config'
        target: 'C:/etc/traefik'
        type: bind
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.port=8080
        # enable this if you want external access
        - traefik.frontend.rule=PathPrefixStrip:/traefik/
    networks:
      - traefik-public

  agent:
    image: portainer/agent:windows1809-amd64
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
      - source: 'C:/ProgramData/docker/volumes'
        target: 'C:/ProgramData/docker/volumes'
        type: bind
    networks:
      - agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == windows

  portainer:
    image: portainer/portainer:windows1809-amd64
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:c:/data
    networks:
      - agent-network
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.frontend.rule=PathPrefixStrip:/portainer/
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.frontend.entryPoints=https
    depends_on:
      - traefik

networks:
  agent-network:
    attachable: true
  traefik-public:
    external: true

volumes:
  portainer-data: